### PR TITLE
Sorting Quotes

### PR DESCRIPTION
**Pull request by galmadar**
- What I did
Added an option to sort the quotes by `Symbol` or `ChangePercent`.
The quotes are sorted according to the `sort-quotes-by` argument (from configuration file or the cli arguments).
Default sort is by `ChangePercent`.
It is a suggestion to expand to functionality of Sorting. according to issue #5 

- How I did it
Changed `sortQuotes` function in `watchlist.go` and "appended" the relevant order by functionality according to `sort-quotes-by` argument.

- How to verify it
In the configuration file (`ticker.yaml`) or as an argument in the CLI, Set `Symbol` as the value of the flag `sort-quotes-by` in order to verify that the quotes are ordered by symbol name.
Set `ChangePercent` (or nothing) as the value of the flag `sort-quotes-by` in order to order the quotes by the change percentage.
Any other value for the flag, will cause to "ignore" any `orderBy`

### CODE REVIEW

**Comment by achannarasappa** [comment]
Thanks for your PR @galmadar!

I noticed a few changes that are needed:

- Unit tests are missing
- commitlint check is failing (have a look [here](https://www.conventionalcommits.org/en/v1.0.0/) for the spec)
- The sorting logic itself could use a bit of refactoring with something like an early return based on the sort order option select. This is something I can take on later too and not a critical change

and have a few suggestions as well:

- **CLI option name** - I suggest renaming the option from `sort-quotes-by` to simply `sort` since at the moment, the only sortable piece of data are the quotes/positions. Further, if we wanted to add the option to sort by position gain for example,  `sort-quotes-by` would not describe that option all too well.
- *CLI Option values* - I'd suggest renaming `symbol` to `alpha` and omitted `changepercent` entirely as an option since it is the default

**Comment by nodesocket** [comment]
This looks great. I requested sorting by symbol name in a issue https://github.com/achannarasappa/ticker/issues/43

**Comment by galmadar** [comment]
Hi @achannarasappa :)
the commitlint check is failing about old commits.. what should I do? open another PR?

In addition, I've added more tests to sort option and I've changed the option name and value (actually the code seems more clean now :) 👍 )

**Comment by achannarasappa** [comment]
@galmadar thanks for the fixes! I'll take a closer look later today

**Comment by galmadar** [comment]
@achannarasappa 
I've opened new PR (#62 ) , much "cleaner" than this one.
Please close this PR if you're OK with that (sorry for the mess 😅 😅 ).

**Comment by achannarasappa** [comment]
Closing this in favor of #62

**Pull request closed without merging**
